spring:
   datasource:
     url: jdbc:mysql://localhost:3306/nht
     username: root
     password: Root@123
     driver-class-name: com.mysql.jdbc.Driver
   jpa:
    properties:
     hibernate:
       dialect: org.hibernate.dialect.MySQL5Dialect
       ddl-auto: update
     show-sql: true
server:
  port: 8080

